#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SESSION="${PROJECT_COCKPIT_TMUX_SESSION:-project-cockpit-4370}"
LOG="${PROJECT_COCKPIT_LOG:-/tmp/project-cockpit-4370.log}"
PORT="${PROJECT_COCKPIT_PORT:-4370}"

export PROJECT_COCKPIT_MULTIMODEL_DATA_DIR="${PROJECT_COCKPIT_MULTIMODEL_DATA_DIR:-${ROOT}/.data}"
TOKEN_DIR="${PROJECT_COCKPIT_MULTIMODEL_DATA_DIR}/workbench-context"
TOKEN_FILE="${PROJECT_COCKPIT_WORKBENCH_CONTEXT_HTTP_MCP_TOKEN_FILE:-${TOKEN_DIR}/darwin-mfc.http-mcp-token}"
mkdir -p "${TOKEN_DIR}"
chmod 700 "${TOKEN_DIR}" 2>/dev/null || true
if [[ -n "${PROJECT_COCKPIT_WORKBENCH_CONTEXT_HTTP_MCP_TOKEN:-}" || -n "${WORKBENCH_CONTEXT_HTTP_MCP_TOKEN:-}" ]]; then
  umask 077
  printf '%s' "${PROJECT_COCKPIT_WORKBENCH_CONTEXT_HTTP_MCP_TOKEN:-${WORKBENCH_CONTEXT_HTTP_MCP_TOKEN:-}}" > "${TOKEN_FILE}"
elif [[ ! -s "${TOKEN_FILE}" ]]; then
  umask 077
  node -e 'process.stdout.write(require("node:crypto").randomBytes(32).toString("base64url"))' > "${TOKEN_FILE}"
fi
chmod 600 "${TOKEN_FILE}" 2>/dev/null || true
unset PROJECT_COCKPIT_WORKBENCH_CONTEXT_HTTP_MCP_TOKEN
unset WORKBENCH_CONTEXT_HTTP_MCP_TOKEN
export PROJECT_COCKPIT_WORKBENCH_CONTEXT_HTTP_MCP_REQUIRE_AUTH="${PROJECT_COCKPIT_WORKBENCH_CONTEXT_HTTP_MCP_REQUIRE_AUTH:-1}"
export PROJECT_COCKPIT_WORKBENCH_CONTEXT_HTTP_MCP_TOKEN_FILE="${TOKEN_FILE}"
export PROJECT_COCKPIT_ALLOW_CROSS_PROJECT_KIMI_ZELLIJ="${PROJECT_COCKPIT_ALLOW_CROSS_PROJECT_KIMI_ZELLIJ:-0}"
export PROJECT_COCKPIT_KIMI_COMMAND="${PROJECT_COCKPIT_KIMI_COMMAND:-${ROOT}/scripts/kimi-cursor-agent}"
# Darwin-MFC should not inherit a cross-project Kimi zellij bridge from Sounio.
export PROJECT_COCKPIT_KIMI_ZELLIJ_PROJECT_SLUG=""
export PROJECT_COCKPIT_KIMI_ZELLIJ_SESSION=""
export PROJECT_COCKPIT_KIMI_ZELLIJ_TAB=""
export PROJECT_COCKPIT_KIMI_ZELLIJ_SSH_HOST=""
export PROJECT_COCKPIT_KIMI_ZELLIJ_SSH_PORT="${PROJECT_COCKPIT_KIMI_ZELLIJ_SSH_PORT:-2222}"
export PROJECT_COCKPIT_KIMI_ZELLIJ_SSH_KEY="${PROJECT_COCKPIT_KIMI_ZELLIJ_SSH_KEY:-/home/devsounio/.ssh/id_ed25519}"
export PROJECT_COCKPIT_KIMI_ZELLIJ_KNOWN_HOSTS="${PROJECT_COCKPIT_KIMI_ZELLIJ_KNOWN_HOSTS:-/home/devsounio/.ssh/known_hosts}"
export PROJECT_COCKPIT_KIMI_ZELLIJ_CHECK_COMMAND=""

if [[ -n "${PROJECT_COCKPIT_KIMI_ZELLIJ_PROJECT_SLUG}" || -n "${PROJECT_COCKPIT_KIMI_ZELLIJ_SESSION}" || -n "${PROJECT_COCKPIT_KIMI_ZELLIJ_TAB}" || -n "${PROJECT_COCKPIT_KIMI_ZELLIJ_SSH_HOST}" || -n "${PROJECT_COCKPIT_KIMI_ZELLIJ_CHECK_COMMAND}" ]]; then
  if [[ -z "${PROJECT_COCKPIT_KIMI_ZELLIJ_PROJECT_SLUG}" || -z "${PROJECT_COCKPIT_KIMI_ZELLIJ_SESSION}" || -z "${PROJECT_COCKPIT_KIMI_ZELLIJ_TAB}" || -z "${PROJECT_COCKPIT_KIMI_ZELLIJ_SSH_HOST}" || -z "${PROJECT_COCKPIT_KIMI_ZELLIJ_CHECK_COMMAND}" ]]; then
    echo "Kimi bridge is partially configured; set PROJECT_COCKPIT_KIMI_ZELLIJ_PROJECT_SLUG, SESSION, TAB, SSH_HOST, and CHECK_COMMAND together." >&2
    exit 1
  fi

  if ! "${PROJECT_COCKPIT_KIMI_ZELLIJ_CHECK_COMMAND}" --check >/tmp/project-cockpit-kimi-check.txt 2>&1; then
    echo "Kimi opt-in bridge check failed:" >&2
    cat /tmp/project-cockpit-kimi-check.txt >&2
    exit 1
  fi
fi

tmux kill-session -t "${SESSION}" 2>/dev/null || true

tmux new-session -d -s "${SESSION}" \
  "cd '${ROOT}' && \
   export PROJECT_COCKPIT_PORT='${PORT}' && \
   export PROJECT_COCKPIT_MULTIMODEL_DATA_DIR='${PROJECT_COCKPIT_MULTIMODEL_DATA_DIR}' && \
   export PROJECT_COCKPIT_WORKBENCH_CONTEXT_HTTP_MCP_REQUIRE_AUTH='${PROJECT_COCKPIT_WORKBENCH_CONTEXT_HTTP_MCP_REQUIRE_AUTH}' && \
   export PROJECT_COCKPIT_WORKBENCH_CONTEXT_HTTP_MCP_TOKEN_FILE='${PROJECT_COCKPIT_WORKBENCH_CONTEXT_HTTP_MCP_TOKEN_FILE}' && \
   export PROJECT_COCKPIT_ALLOW_CROSS_PROJECT_KIMI_ZELLIJ='${PROJECT_COCKPIT_ALLOW_CROSS_PROJECT_KIMI_ZELLIJ}' && \
   export PROJECT_COCKPIT_KIMI_COMMAND='${PROJECT_COCKPIT_KIMI_COMMAND}' && \
   export PROJECT_COCKPIT_KIMI_ZELLIJ_PROJECT_SLUG='${PROJECT_COCKPIT_KIMI_ZELLIJ_PROJECT_SLUG}' && \
   export PROJECT_COCKPIT_KIMI_ZELLIJ_SESSION='${PROJECT_COCKPIT_KIMI_ZELLIJ_SESSION}' && \
   export PROJECT_COCKPIT_KIMI_ZELLIJ_TAB='${PROJECT_COCKPIT_KIMI_ZELLIJ_TAB}' && \
   export PROJECT_COCKPIT_KIMI_ZELLIJ_PANE='${PROJECT_COCKPIT_KIMI_ZELLIJ_PANE:-}' && \
   export PROJECT_COCKPIT_KIMI_ZELLIJ_SSH_HOST='${PROJECT_COCKPIT_KIMI_ZELLIJ_SSH_HOST}' && \
   export PROJECT_COCKPIT_KIMI_ZELLIJ_SSH_PORT='${PROJECT_COCKPIT_KIMI_ZELLIJ_SSH_PORT}' && \
   export PROJECT_COCKPIT_KIMI_ZELLIJ_SSH_KEY='${PROJECT_COCKPIT_KIMI_ZELLIJ_SSH_KEY}' && \
   export PROJECT_COCKPIT_KIMI_ZELLIJ_KNOWN_HOSTS='${PROJECT_COCKPIT_KIMI_ZELLIJ_KNOWN_HOSTS}' && \
   export PROJECT_COCKPIT_KIMI_ZELLIJ_CHECK_COMMAND='${PROJECT_COCKPIT_KIMI_ZELLIJ_CHECK_COMMAND}' && \
   node server/index.mjs >> '${LOG}' 2>&1"

echo "Project Cockpit running in tmux session ${SESSION}"
echo "Backend: http://127.0.0.1:${PORT}"
echo "HTTP MCP auth: required (${TOKEN_FILE})"
if [[ -n "${PROJECT_COCKPIT_KIMI_ZELLIJ_PROJECT_SLUG}" ]]; then
  echo "Kimi bridge: ${PROJECT_COCKPIT_KIMI_ZELLIJ_PROJECT_SLUG}:${PROJECT_COCKPIT_KIMI_ZELLIJ_SESSION}:${PROJECT_COCKPIT_KIMI_ZELLIJ_TAB}:${PROJECT_COCKPIT_KIMI_ZELLIJ_PANE:-focused-pane}"
elif [[ -n "${PROJECT_COCKPIT_KIMI_COMMAND}" ]]; then
  echo "Kimi bridge: local-command (${PROJECT_COCKPIT_KIMI_COMMAND})"
else
  echo "Kimi bridge: disabled for Darwin-MFC until a project-local bridge is configured"
fi
