#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'EOF'
usage: publish-node-local-images.sh [--registry-host ttl.sh] [--prefix sounio-lab] [--ttl 24h] [--plain-http] [--out /path/to/image-defaults.env]

Publishes the current node-local localhost/... images to a pullable registry and
writes a defaults file suitable for workspace-platform scaffolding.

The current safe default targets ttl.sh for a short-lived, auth-free transition
path. It does not mutate live manifests on its own.
EOF
}

require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "missing command: $1" >&2
    exit 1
  }
}

registry_host="ttl.sh"
prefix="sounio-lab"
ttl="24h"
out_file=""
plain_http="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --registry-host)
      registry_host="$2"
      shift 2
      ;;
    --prefix)
      prefix="$2"
      shift 2
      ;;
    --ttl)
      ttl="$2"
      shift 2
      ;;
    --out)
      out_file="$2"
      shift 2
      ;;
    --plain-http)
      plain_http="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      echo "unknown arg: $1" >&2
      exit 1
      ;;
  esac
done

require podman
require skopeo
require sudo
require ctr

timestamp="$(date +%Y%m%d%H%M%S)"
nonce="$(python3 - <<'PY'
import secrets
print(secrets.token_hex(3))
PY
)"

if [[ -z "${out_file}" ]]; then
  out_file="/tmp/workspace-platform-image-defaults-${timestamp}.env"
fi

ensure_in_podman() {
  local image_ref="$1"
  if podman image exists "${image_ref}"; then
    return 0
  fi

  local tmpdir
  tmpdir="$(mktemp -d)"
  trap 'rm -rf "${tmpdir}"' RETURN
  sudo ctr -n k8s.io images export "${tmpdir}/image.tar" "${image_ref}" >/dev/null
  podman load -i "${tmpdir}/image.tar" >/dev/null
  rm -rf "${tmpdir}"
  trap - RETURN
}

publish_one() {
  local src="$1"
  local repo_name="$2"
  local dest="docker://${registry_host}/${prefix}-${repo_name}-${timestamp}-${nonce}:${ttl}"
  ensure_in_podman "${src}"
  echo "[info] publishing ${src} -> ${dest}" >&2
  if [[ "${plain_http}" == "true" ]]; then
    skopeo copy --insecure-policy --dest-tls-verify=false "containers-storage:${src}" "${dest}" >/dev/null
  else
    skopeo copy --insecure-policy "containers-storage:${src}" "${dest}" >/dev/null
  fi
  printf '%s\n' "${registry_host}/${prefix}-${repo_name}-${timestamp}-${nonce}:${ttl}"
}

project_cockpit_ref="$(publish_one "localhost/project-cockpit:20260406-8" "project-cockpit")"
ide_ref="$(publish_one "localhost/sounio-workspace-ide:0406231500" "sounio-workspace-ide")"
ssh_ref="$(publish_one "localhost/beagle-workspace-ssh:b216" "beagle-workspace-ssh")"

cat >"${out_file}" <<EOF
# Generated by publish-node-local-images.sh on ${timestamp}
DEFAULT_PROJECT_COCKPIT_IMAGE=${project_cockpit_ref}
DEFAULT_IDE_IMAGE=${ide_ref}
DEFAULT_SSH_IMAGE=${ssh_ref}
EOF

printf '[ok] wrote %s\n' "${out_file}" >&2
cat "${out_file}"
