FROM docker.io/gitpod/openvscode-server@sha256:236821ee7c8f9284b7f94799d4b66bc465926f435ac323af03e50bfb503c1ca1

USER root

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      bash \
      build-essential \
      ca-certificates \
      clang \
      cmake \
      curl \
      docker.io \
      file \
      fonts-liberation \
      gh \
      git \
      jq \
      libasound2 \
      libatk-bridge2.0-0 \
      libatk1.0-0 \
      libatspi2.0-0 \
      libcairo2 \
      libcups2 \
      libdbus-1-3 \
      libdrm2 \
      libgbm1 \
      libglib2.0-0 \
      libnspr4 \
      libnss3 \
      libpango-1.0-0 \
      libx11-6 \
      libx11-xcb1 \
      libxcb1 \
      libxcomposite1 \
      libxdamage1 \
      libxext6 \
      libxfixes3 \
      libxkbcommon0 \
      libxrandr2 \
      libxshmfence1 \
      lld \
      llvm \
      make \
      ninja-build \
      pkg-config \
      python3 \
      python3-pip \
      ripgrep \
      sudo \
      tmux \
      zsh \
    && rm -rf /var/lib/apt/lists/*

RUN usermod -s /usr/bin/zsh openvscode-server

USER openvscode-server
