apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sounio-workspace-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  volumeMode: Filesystem
  storageClassName: ceph-rbd-ssd
