apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-nvme-r740-scratch-pv
spec:
  capacity:
    storage: 1400Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-nvme-r740
  local:
    path: /mnt/hpc-local-nvme/scratch
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - r740-proxmox
