// siogen.mjs — Phase B: generate the Sounio driver that runs the functor F over
// one dialogue trajectory. Templates the (proven) emit_turn pattern: declare each
// turn's content[8]/uncertainty[8] arrays, then call emit_turn per index with the
// right prev/cur/next (endpoints reuse cur). The Node pipeline runs `souc` on this
// and parses the TELEM blocks. Keeping the trajectory inlined avoids any reliance
// on Sounio file IO and the fixed-array-length friction.

// A Sounio f64 literal: a plain decimal, never exponential (Sounio's lexer wants
// a decimal point and no e-notation). 9 places is ample for projected content.
function f64lit(x) {
  if (!Number.isFinite(x)) return "0.0";
  return Number(x).toFixed(9);
}

function arr8(name, vals) {
  const v = (vals || []).slice(0, 8);
  while (v.length < 8) v.push(0);
  return `    let ${name}: [f64; 8] = [${v.map(f64lit).join(", ")}]`;
}

/**
 * Generate the driver .sio source for a trajectory.
 * @param {Array<{speaker:number, content:number[], uncertainty:number[]}>} trajectory
 * @param {{ruptureThresh?:number}} [opts]
 * @returns {string} Sounio source
 */
export function genDriverSio(trajectory, opts = {}) {
  const thresh = f64lit(opts.ruptureThresh ?? 0.15);
  const n = trajectory.length;
  const lines = [];
  lines.push("// generated by apps/cognitive-telemetry — Tapestry Phase B driver");
  lines.push("use cybernetic::dialogue_tapestry::{emit_turn}");
  lines.push("");
  lines.push("fn main() -> i32 with IO, Mut, Div, Panic {");
  for (let i = 0; i < n; i++) {
    lines.push(arr8(`c${i}`, trajectory[i].content));
    lines.push(arr8(`u${i}`, trajectory[i].uncertainty));
  }
  for (let i = 0; i < n; i++) {
    const hasPrev = i > 0;
    const hasNext = i < n - 1;
    const prev = hasPrev ? `c${i - 1}` : `c${i}`;
    const next = hasNext ? `c${i + 1}` : `c${i}`;
    const sp = Math.trunc(trajectory[i].speaker) || 0;
    lines.push(
      `    emit_turn(${i}, ${sp}, ${prev}, c${i}, ${next}, u${i}, ${hasPrev}, ${hasNext}, ${thresh})`,
    );
  }
  lines.push("    0");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

export default genDriverSio;
