apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-checkpoints
  namespace: beagle
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-ssd-checkpoints
  resources:
    requests:
      storage: 1Ti
