apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-datasets-clone
  namespace: beagle
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-ssd-datasets
  resources:
    requests:
      storage: 2Ti
  dataSource:
    apiGroup: ""
    kind: PersistentVolumeClaim
    name: training-datasets
