apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-scratch
  namespace: beagle
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-ssd-scratch
  resources:
    requests:
      storage: 500Gi
