apiVersion: v1
kind: ResourceQuota
metadata:
  name: darwin-platform-quota
  namespace: darwin-platform
spec:
  hard:
    configmaps: "40"
    limits.cpu: "12"
    limits.memory: 24Gi
    persistentvolumeclaims: "0"
    pods: "40"
    requests.cpu: "6"
    requests.memory: 12Gi
    secrets: "40"
    services: "20"
    services.loadbalancers: "1"
    services.nodeports: "1"
