apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
type: Opaque
stringData:
  client_id: tskey-client-your-oauth-client-id
  client_secret: tskey-client-your-oauth-client-secret
