# Formulário de hospital geral / clínica médica — (nome em português, generic name do label FDA)
# Escolhido pelo que aparece num plantão: anticoagulação, antimicrobianos, analgesia/sedação,
# cardiovascular, endócrino, neuro, GI, vasoativos, eletrólitos, psiquiatria, respiratório.
FORMULARIO = [
    # anticoagulação / hematologia
    ("enoxaparina", "enoxaparin sodium"), ("heparina", "heparin sodium"),
    ("varfarina", "warfarin sodium"), ("rivaroxabana", "rivaroxaban"),
    ("apixabana", "apixaban"), ("dabigatrana", "dabigatran etexilate mesylate"),
    ("edoxabana", "edoxaban"), ("fondaparinux", "fondaparinux sodium"),
    ("alteplase", "alteplase"), ("tenecteplase", "tenecteplase"),
    ("acido tranexamico", "tranexamic acid"), ("protamina", "protamine sulfate"),
    ("fitomenadiona", "phytonadione"), ("clopidogrel", "clopidogrel bisulfate"),
    ("ticagrelor", "ticagrelor"), ("prasugrel", "prasugrel"),
    ("aspirina", "aspirin"), ("idarucizumabe", "idarucizumab"),
    # antimicrobianos
    ("amoxicilina", "amoxicillin"), ("amoxicilina clavulanato", "amoxicillin and clavulanate potassium"),
    ("ampicilina", "ampicillin"), ("ampicilina sulbactam", "ampicillin and sulbactam"),
    ("piperacilina tazobactam", "piperacillin and tazobactam"),
    ("cefazolina", "cefazolin"), ("cefalexina", "cephalexin"),
    ("ceftriaxona", "ceftriaxone"), ("cefepima", "cefepime"),
    ("ceftazidima", "ceftazidime"), ("cefuroxima", "cefuroxime"),
    ("meropenem", "meropenem"), ("imipenem", "imipenem and cilastatin"),
    ("ertapenem", "ertapenem"), ("aztreonam", "aztreonam"),
    ("vancomicina", "vancomycin hydrochloride"), ("teicoplanina", "teicoplanin"),
    ("linezolida", "linezolid"), ("daptomicina", "daptomycin"),
    ("clindamicina", "clindamycin"), ("metronidazol", "metronidazole"),
    ("azitromicina", "azithromycin"), ("claritromicina", "clarithromycin"),
    ("levofloxacino", "levofloxacin"), ("ciprofloxacino", "ciprofloxacin"),
    ("moxifloxacino", "moxifloxacin"), ("gentamicina", "gentamicin sulfate"),
    ("amicacina", "amikacin"), ("polimixina b", "polymyxin b sulfate"),
    ("colistina", "colistimethate sodium"), ("tigeciclina", "tigecycline"),
    ("doxiciclina", "doxycycline"), ("sulfametoxazol trimetoprima", "sulfamethoxazole and trimethoprim"),
    ("nitrofurantoina", "nitrofurantoin"), ("fosfomicina", "fosfomycin tromethamine"),
    ("fluconazol", "fluconazole"), ("voriconazol", "voriconazole"),
    ("anfotericina b", "amphotericin b"), ("caspofungina", "caspofungin acetate"),
    ("micafungina", "micafungin sodium"), ("aciclovir", "acyclovir"),
    ("oseltamivir", "oseltamivir phosphate"), ("ganciclovir", "ganciclovir"),
    ("isoniazida", "isoniazid"), ("rifampicina", "rifampin"),
    ("pirazinamida", "pyrazinamide"), ("etambutol", "ethambutol hydrochloride"),
    # analgesia / sedação / anestesia
    ("morfina", "morphine sulfate"), ("fentanila", "fentanyl citrate"),
    ("metadona", "methadone hydrochloride"), ("tramadol", "tramadol hydrochloride"),
    ("codeina", "codeine phosphate"), ("oxicodona", "oxycodone hydrochloride"),
    ("naloxona", "naloxone hydrochloride"), ("dipirona", "metamizole"),
    ("paracetamol", "acetaminophen"), ("ibuprofeno", "ibuprofen"),
    ("cetoprofeno", "ketoprofen"), ("cetorolaco", "ketorolac tromethamine"),
    ("diclofenaco", "diclofenac sodium"), ("midazolam", "midazolam hydrochloride"),
    ("diazepam", "diazepam"), ("lorazepam", "lorazepam"),
    ("propofol", "propofol"), ("etomidato", "etomidate"),
    ("cetamina", "ketamine hydrochloride"), ("dexmedetomidina", "dexmedetomidine hydrochloride"),
    ("succinilcolina", "succinylcholine chloride"), ("rocuronio", "rocuronium bromide"),
    ("flumazenil", "flumazenil"), ("lidocaina", "lidocaine hydrochloride"),
    ("bupivacaina", "bupivacaine hydrochloride"), ("gabapentina", "gabapentin"),
    ("pregabalina", "pregabalin"), ("amitriptilina", "amitriptyline hydrochloride"),
    # cardiovascular
    ("noradrenalina", "norepinephrine bitartrate"), ("adrenalina", "epinephrine"),
    ("dopamina", "dopamine hydrochloride"), ("dobutamina", "dobutamine hydrochloride"),
    ("vasopressina", "vasopressin"), ("milrinona", "milrinone lactate"),
    ("nitroglicerina", "nitroglycerin"), ("nitroprussiato", "sodium nitroprusside"),
    ("amiodarona", "amiodarone hydrochloride"), ("adenosina", "adenosine"),
    ("digoxina", "digoxin"), ("metoprolol", "metoprolol tartrate"),
    ("atenolol", "atenolol"), ("carvedilol", "carvedilol"),
    ("bisoprolol", "bisoprolol fumarate"), ("propranolol", "propranolol hydrochloride"),
    ("esmolol", "esmolol hydrochloride"), ("verapamil", "verapamil hydrochloride"),
    ("diltiazem", "diltiazem hydrochloride"), ("anlodipino", "amlodipine besylate"),
    ("nifedipino", "nifedipine"), ("captopril", "captopril"),
    ("enalapril", "enalapril maleate"), ("lisinopril", "lisinopril"),
    ("losartana", "losartan potassium"), ("valsartana", "valsartan"),
    ("hidralazina", "hydralazine hydrochloride"), ("clonidina", "clonidine hydrochloride"),
    ("furosemida", "furosemide"), ("hidroclorotiazida", "hydrochlorothiazide"),
    ("espironolactona", "spironolactone"), ("sacubitril valsartana", "sacubitril and valsartan"),
    ("atorvastatina", "atorvastatin calcium"), ("sinvastatina", "simvastatin"),
    ("rosuvastatina", "rosuvastatin calcium"),
    # endócrino / metabólico
    ("insulina regular", "insulin human"), ("insulina glargina", "insulin glargine"),
    ("insulina nph", "insulin human isophane"), ("insulina lispro", "insulin lispro"),
    ("metformina", "metformin hydrochloride"), ("gliclazida", "gliclazide"),
    ("glibenclamida", "glyburide"), ("empagliflozina", "empagliflozin"),
    ("dapagliflozina", "dapagliflozin"), ("liraglutida", "liraglutide"),
    ("levotiroxina", "levothyroxine sodium"), ("metimazol", "methimazole"),
    ("propiltiouracila", "propylthiouracil"), ("hidrocortisona", "hydrocortisone"),
    ("prednisona", "prednisone"), ("metilprednisolona", "methylprednisolone"),
    ("dexametasona", "dexamethasone"), ("fludrocortisona", "fludrocortisone acetate"),
    ("glucagon", "glucagon"), ("octreotida", "octreotide acetate"),
    # neuro
    ("fenitoina", "phenytoin sodium"), ("fenobarbital", "phenobarbital"),
    ("acido valproico", "valproate sodium"), ("levetiracetam", "levetiracetam"),
    ("carbamazepina", "carbamazepine"), ("lamotrigina", "lamotrigine"),
    ("manitol", "mannitol"), ("nimodipino", "nimodipine"),
    ("tiamina", "thiamine hydrochloride"), ("levodopa carbidopa", "carbidopa and levodopa"),
    ("sumatriptano", "sumatriptan succinate"),
    # GI
    ("omeprazol", "omeprazole"), ("pantoprazol", "pantoprazole sodium"),
    ("esomeprazol", "esomeprazole magnesium"), ("ranitidina", "ranitidine hydrochloride"),
    ("ondansetrona", "ondansetron hydrochloride"), ("metoclopramida", "metoclopramide hydrochloride"),
    ("bromoprida", "bromopride"), ("dimenidrinato", "dimenhydrinate"),
    ("lactulose", "lactulose"), ("terlipressina", "terlipressin"),
    ("octreotida gi", "octreotide acetate"), ("mesalazina", "mesalamine"),
    ("ursodiol", "ursodiol"), ("n acetilcisteina", "acetylcysteine"),
    # respiratório
    ("salbutamol", "albuterol sulfate"), ("ipratropio", "ipratropium bromide"),
    ("budesonida", "budesonide"), ("formoterol", "formoterol fumarate"),
    ("tiotropio", "tiotropium bromide"), ("teofilina", "theophylline"),
    ("sulfato de magnesio", "magnesium sulfate"),
    # psiquiatria
    ("haloperidol", "haloperidol"), ("quetiapina", "quetiapine fumarate"),
    ("olanzapina", "olanzapine"), ("risperidona", "risperidone"),
    ("clorpromazina", "chlorpromazine hydrochloride"), ("sertralina", "sertraline hydrochloride"),
    ("fluoxetina", "fluoxetine hydrochloride"), ("escitalopram", "escitalopram oxalate"),
    ("venlafaxina", "venlafaxine hydrochloride"), ("mirtazapina", "mirtazapine"),
    ("litio", "lithium carbonate"), ("clonazepam", "clonazepam"),
    ("tiapride", "tiapride"),
    # eletrólitos / suporte / diversos
    ("cloreto de potassio", "potassium chloride"), ("bicarbonato de sodio", "sodium bicarbonate"),
    ("gluconato de calcio", "calcium gluconate"), ("cloreto de sodio", "sodium chloride"),
    ("albumina", "albumin human"), ("alopurinol", "allopurinol"),
    ("colchicina", "colchicine"), ("hidroxicloroquina", "hydroxychloroquine sulfate"),
    ("azatioprina", "azathioprine"), ("micofenolato", "mycophenolate mofetil"),
    ("tacrolimo", "tacrolimus"), ("ciclosporina", "cyclosporine"),
    ("rituximabe", "rituximab"), ("imunoglobulina", "immune globulin"),
    ("eritropoetina", "epoetin alfa"), ("filgrastim", "filgrastim"),
    ("acido folico", "folic acid"), ("sulfato ferroso", "ferrous sulfate"),
    ("vitamina b12", "cyanocobalamin"), ("vitamina d", "cholecalciferol"),
    ("calcitriol", "calcitriol"), ("sevelamer", "sevelamer carbonate"),
    ("desmopressina", "desmopressin acetate"), ("cetamina s", "esketamine"),
]
