#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/../../../.." && pwd)
DOC_ROOT="${REPO_ROOT}/docs/darwin/hpc"
CONTRACT_ROOT="${DOC_ROOT}/contracts"
ARTIFACT_ROOT=${ARTIFACT_ROOT:-"${REPO_ROOT}/.artifacts/darwin-hpc"}
DARWIN_V2_ROOT=${DARWIN_V2_ROOT:-/root/darwin-v2}
PHASE_ROOT="${ARTIFACT_ROOT}/phase-b10"
RUN_ID=${RUN_ID:-$(date +%Y%m%d-%H%M%S)}
RESULT_DIR="${PHASE_ROOT}/${RUN_ID}/object-artifacts"
RGW_TARGET_ENV=${RGW_TARGET_ENV:-"${CONTRACT_ROOT}/rgw-artifact-target.env"}
RGW_ENDPOINT_DEFAULT=${RGW_ENDPOINT_DEFAULT:-http://192.168.3.171:7480}
RGW_BUCKET_DEFAULT=${RGW_BUCKET_DEFAULT:-darwin-hpc-artifacts}
RGW_UID_DEFAULT=${RGW_UID_DEFAULT:-darwin-hpc-artifact-publisher}
RGW_VELERO_BUCKET_DEFAULT=${RGW_VELERO_BUCKET_DEFAULT:-darwin-k8s-backups}
PUBLICATION_TARGET_ID_DEFAULT=${PUBLICATION_TARGET_ID_DEFAULT:-hpc-artifacts-v1}
SOURCE_PROFILE_ID=${SOURCE_PROFILE_ID:-cpu-short-v1}

readonly SCRIPT_DIR REPO_ROOT DOC_ROOT CONTRACT_ROOT ARTIFACT_ROOT DARWIN_V2_ROOT PHASE_ROOT RESULT_DIR RGW_TARGET_ENV

require_cmd() {
  local cmd=$1
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "missing required command: ${cmd}" >&2
    exit 1
  fi
}

resolve_b96_run_id() {
  awk '
    /^canonical_run_id:/ { in_block=1; next }
    in_block && /^  [^ ]/ && $1 != "B9.6:" { in_block=0 }
    in_block && /^  B9\.6:/ { print $2; exit }
  ' "${DARWIN_V2_ROOT}/session/session_state.yaml"
}

ensure_python_dep() {
  if python3 - <<'PY' >/dev/null 2>&1
import importlib.util
import sys
sys.exit(0 if importlib.util.find_spec("boto3") and importlib.util.find_spec("botocore") else 1)
PY
  then
    return 0
  fi

  export DEBIAN_FRONTEND=noninteractive
  apt-get install -y python3-boto3 python3-botocore >/dev/null
}

ensure_green_cluster() {
  local node
  for node in t560-proxmox r770-proxmox 5860-proxmox; do
    local ready
    ready=$(kubectl get node "${node}" -o jsonpath='{range .status.conditions[?(@.type=="Ready")]}{.status}{end}')
    [[ "${ready}" == "True" ]] || {
      echo "node not Ready: ${node}" >&2
      exit 1
    }
  done

  local coredns_ready
  coredns_ready=$(kubectl -n kube-system get deploy coredns -o jsonpath='{.status.readyReplicas}/{.status.replicas}' 2>/dev/null || true)
  [[ "${coredns_ready%%/*}" == "${coredns_ready##*/}" ]] || {
    echo "CoreDNS not fully ready: ${coredns_ready}" >&2
    exit 1
  }
}

materialize_rgw_target() {
  local user_json
  local endpoint
  local bucket
  local uid
  local velero_bucket
  local publication_target_id
  local access_key
  local secret_key

  endpoint=${RGW_ENDPOINT_DEFAULT}
  bucket=${RGW_BUCKET_DEFAULT}
  uid=${RGW_UID_DEFAULT}
  velero_bucket=${RGW_VELERO_BUCKET_DEFAULT}
  publication_target_id=${PUBLICATION_TARGET_ID_DEFAULT}

  user_json=$(radosgw-admin user info --uid="${uid}" 2>/dev/null || true)
  if [[ -z "${user_json}" ]]; then
    user_json=$(radosgw-admin user create \
      --uid="${uid}" \
      --display-name="Darwin HPC Artifact Publisher")
  fi

  access_key=$(python3 - <<'PY' "${user_json}"
import json
import sys
data = json.loads(sys.argv[1])
print(data["keys"][0]["access_key"])
PY
)
  secret_key=$(python3 - <<'PY' "${user_json}"
import json
import sys
data = json.loads(sys.argv[1])
print(data["keys"][0]["secret_key"])
PY
)

  cat > "${RGW_TARGET_ENV}" <<EOF
# B10.1 dedicated object target contract
# generated by run_object_artifact_publication.sh
RGW_ENDPOINT=${endpoint}
RGW_BUCKET=${bucket}
RGW_UID=${uid}
RGW_VELERO_BUCKET=${velero_bucket}
PUBLICATION_TARGET_ID=${publication_target_id}
SOURCE_PROFILE_ID=${SOURCE_PROFILE_ID}
RGW_ACCESS_KEY=${access_key}
RGW_SECRET_KEY=${secret_key}
EOF
  chmod 0600 "${RGW_TARGET_ENV}"
}

collect_final_health() {
  {
    echo "captured_at=$(date -Iseconds)"
    echo
    echo "## kubernetes-nodes"
    kubectl get nodes -o wide || true
    echo
    if command -v cilium >/dev/null 2>&1; then
      echo "## cilium"
      cilium status --wait --wait-duration=30s || true
      echo
    fi
    echo "## coredns"
    kubectl -n kube-system get deploy coredns || true
    echo
    echo "## slurm-units"
    for unit in slurmctld slurmrestd munge; do
      printf '%s=%s\n' "${unit}" "$(systemctl is-active "${unit}" 2>/dev/null || true)"
    done
    echo
    if command -v scontrol >/dev/null 2>&1; then
      echo "## scontrol-ping"
      scontrol ping || true
      echo
    fi
    if command -v sinfo >/dev/null 2>&1; then
      echo "## slurm-sinfo"
      sinfo -N -l || true
      echo
    fi
  } > "${RESULT_DIR}/final-cluster-health.txt"
}

write_result() {
  local manifest_path="${RESULT_DIR}/object-manifest.json"
  local object_bucket
  local object_key
  local publication_time
  local published_checksum
  local job_id
  local run_label

  object_bucket=$(jq -r '.object_bucket' "${manifest_path}")
  object_key=$(jq -r '.object_key' "${manifest_path}")
  publication_time=$(jq -r '.publication_time' "${manifest_path}")
  published_checksum=$(jq -r '.published_checksum' "${manifest_path}")
  job_id=$(jq -r '.job_id' "${manifest_path}")
  run_label=$(jq -r '.run_label' "${manifest_path}")

  cat > "${RESULT_DIR}/B101_RESULT.md" <<EOF
# B10.1 Object-backed Artifact Publication Result

## Status
GO

## Decision
one real approved cpu-short-v1 bundle was published into a dedicated RGW bucket
with deterministic keys, enriched manifest metadata, and checksum validation.

## Publication
- run id: ${RUN_ID}
- publication target id: ${PUBLICATION_TARGET_ID_DEFAULT}
- bucket: ${object_bucket}
- primary object key: ${object_key}
- source job id: ${job_id}
- run label: ${run_label}
- publication time: ${publication_time}
- published checksum: ${published_checksum}
EOF
}

main() {
  local source_run_id
  local source_dir
  local source_manifest_json

  require_cmd jq
  require_cmd kubectl
  require_cmd python3
  require_cmd sha256sum
  require_cmd radosgw-admin
  require_cmd curl

  if [[ -z "${KUBECONFIG:-}" && -f /etc/kubernetes/admin.conf ]]; then
    export KUBECONFIG=/etc/kubernetes/admin.conf
  fi

  source_run_id=${SOURCE_RUN_ID:-$(resolve_b96_run_id)}
  [[ -n "${source_run_id}" ]] || {
    echo "failed to resolve canonical B9.6 run id" >&2
    exit 1
  }

  source_dir="${DARWIN_V2_ROOT}/phase-b9/${source_run_id}/research-admission"
  source_manifest_json="${source_dir}/artifact-via-research.txt"

  mkdir -p "${RESULT_DIR}"
  exec > >(tee "${RESULT_DIR}/publish-log.txt") 2>&1

  ensure_green_cluster
  ensure_python_dep
  materialize_rgw_target
  source "${RGW_TARGET_ENV}"

  [[ "${RGW_BUCKET}" != "${RGW_VELERO_BUCKET}" ]] || {
    echo "artifact bucket must not match Velero bucket" >&2
    exit 1
  }
  [[ -n "${RGW_ACCESS_KEY}" && -n "${RGW_SECRET_KEY}" ]] || {
    echo "RGW credentials are empty" >&2
    exit 1
  }
  [[ -f "${source_manifest_json}" ]] || {
    echo "missing source manifest: ${source_manifest_json}" >&2
    exit 1
  }

  export RUN_ID RESULT_DIR REPO_ROOT source_run_id
  export SOURCE_MANIFEST_JSON="${source_manifest_json}"
  export RGW_ENDPOINT RGW_BUCKET RGW_ACCESS_KEY RGW_SECRET_KEY RGW_VELERO_BUCKET
  export PUBLICATION_TARGET_ID SOURCE_PROFILE_ID

  python3 - <<'PY'
import hashlib
import json
import mimetypes
import os
from datetime import datetime, timezone
from pathlib import Path

import boto3
import botocore.exceptions

source_manifest_path = Path(os.environ["SOURCE_MANIFEST_JSON"])
source = json.loads(source_manifest_path.read_text())["body"]

profile_id = source["profile_id"]
expected_profile = os.environ["SOURCE_PROFILE_ID"]
if profile_id != expected_profile:
    raise SystemExit(f"source profile mismatch: expected {expected_profile}, got {profile_id}")

job_id = int(source["job_id"])
run_label = source["run_label"]
bucket = os.environ["RGW_BUCKET"]
endpoint = os.environ["RGW_ENDPOINT"]
publication_target_id = os.environ["PUBLICATION_TARGET_ID"]
result_dir = Path(os.environ["RESULT_DIR"])
source_run_id = os.environ["source_run_id"]

artifact_path = Path(source["artifact_path"])
stdout_path = Path(source["stdout_path"])
stderr_path = Path(source["stderr_path"])
for path in (artifact_path, stdout_path, stderr_path):
    if not path.exists():
        raise SystemExit(f"missing source file: {path}")

base_prefix = f"hpc/{profile_id}/{job_id}/{run_label}"
publication_time = datetime.now(timezone.utc).astimezone().isoformat()

def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()

def sha256_path(path: Path) -> str:
    return sha256_bytes(path.read_bytes())

def content_type_for(path: Path, fallback: str) -> str:
    guessed = mimetypes.guess_type(str(path))[0]
    return guessed or fallback

entries = [
    {
        "artifact_kind": "artifact",
        "local_path": str(artifact_path),
        "object_key": f"{base_prefix}/artifact.bin",
        "content_type": source.get("artifact_mime_type") or content_type_for(artifact_path, "application/octet-stream"),
        "published_checksum": sha256_path(artifact_path),
        "size_bytes": artifact_path.stat().st_size,
    },
    {
        "artifact_kind": "stdout",
        "local_path": str(stdout_path),
        "object_key": f"{base_prefix}/stdout.txt",
        "content_type": "text/plain; charset=utf-8",
        "published_checksum": sha256_path(stdout_path),
        "size_bytes": stdout_path.stat().st_size,
    },
    {
        "artifact_kind": "stderr",
        "local_path": str(stderr_path),
        "object_key": f"{base_prefix}/stderr.txt",
        "content_type": "text/plain; charset=utf-8",
        "published_checksum": sha256_path(stderr_path),
        "size_bytes": stderr_path.stat().st_size,
    },
]

artifact_entry = next(entry for entry in entries if entry["artifact_kind"] == "artifact")
manifest_object_key = f"{base_prefix}/artifact-manifest.json"
manifest = {
    "manifest_format": "darwin-b101-object-artifact-v1",
    "publication_target_id": publication_target_id,
    "source_phase": "B9.6",
    "source_run_id": source_run_id,
    "source_manifest_path": str(source_manifest_path),
    "job_id": job_id,
    "job_name": source["job_name"],
    "profile_id": profile_id,
    "run_label": run_label,
    "state": source["state"],
    "submit_time": source["submit_time"],
    "start_time": source["start_time"],
    "end_time": source["end_time"],
    "exit_code": source["exit_code"],
    "object_bucket": bucket,
    "object_key": artifact_entry["object_key"],
    "manifest_object_key": manifest_object_key,
    "publication_time": publication_time,
    "published_checksum": artifact_entry["published_checksum"],
    "published_objects": [
        {
            "artifact_kind": entry["artifact_kind"],
            "object_key": entry["object_key"],
            "content_type": entry["content_type"],
            "published_checksum": entry["published_checksum"],
            "size_bytes": entry["size_bytes"],
        }
        for entry in entries
    ],
}

manifest_path = result_dir / "object-manifest.json"
manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
manifest_entry = {
    "artifact_kind": "manifest",
    "local_path": str(manifest_path),
    "object_key": manifest_object_key,
    "content_type": "application/json",
    "published_checksum": sha256_path(manifest_path),
    "size_bytes": manifest_path.stat().st_size,
}
entries.append(manifest_entry)

s3 = boto3.client(
    "s3",
    endpoint_url=endpoint,
    aws_access_key_id=os.environ["RGW_ACCESS_KEY"],
    aws_secret_access_key=os.environ["RGW_SECRET_KEY"],
    region_name="us-east-1",
)

try:
    s3.head_bucket(Bucket=bucket)
except botocore.exceptions.ClientError as exc:
    code = exc.response.get("Error", {}).get("Code", "")
    if code in {"404", "NoSuchBucket", "NotFound"}:
        s3.create_bucket(Bucket=bucket)
    else:
        raise

for entry in entries:
    path = Path(entry["local_path"])
    body = path.read_bytes()
    s3.put_object(
        Bucket=bucket,
        Key=entry["object_key"],
        Body=body,
        ContentType=entry["content_type"],
        Metadata={
            "sha256": entry["published_checksum"],
            "job-id": str(job_id),
            "profile-id": profile_id,
            "run-label": run_label,
            "artifact-kind": entry["artifact_kind"],
        },
    )

head_records = []
for entry in entries:
    head = s3.head_object(Bucket=bucket, Key=entry["object_key"])
    remote_body = s3.get_object(Bucket=bucket, Key=entry["object_key"])["Body"].read()
    remote_sha = sha256_bytes(remote_body)
    if remote_sha != entry["published_checksum"]:
      raise SystemExit(f"checksum mismatch for {entry['object_key']}: local={entry['published_checksum']} remote={remote_sha}")
    head_records.append(
        {
            "artifact_kind": entry["artifact_kind"],
            "object_bucket": bucket,
            "object_key": entry["object_key"],
            "content_length": head["ContentLength"],
            "content_type": head.get("ContentType", ""),
            "etag": head.get("ETag", ""),
            "metadata": head.get("Metadata", {}),
            "verified_checksum": remote_sha,
        }
    )

(result_dir / "object-head.txt").write_text(json.dumps(head_records, indent=2, sort_keys=True) + "\n", encoding="utf-8")
manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
PY

  collect_final_health
  write_result
  echo "B10.1 object artifact publication artifacts written to ${RESULT_DIR}"
}

main "$@"
