#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/../../../.." && pwd)
DOC_ROOT="${REPO_ROOT}/docs/darwin/hpc"
CONTRACT_ROOT="${DOC_ROOT}/contracts"
ARTIFACT_ROOT=${ARTIFACT_ROOT:-"${REPO_ROOT}/.artifacts/darwin-hpc"}
PHASE_ROOT="${ARTIFACT_ROOT}/phase-b10"
RUN_ID=${RUN_ID:-$(date +%Y%m%d-%H%M%S)}
RESULT_DIR="${PHASE_ROOT}/${RUN_ID}/object-artifacts"
RGW_TARGET_ENV=${RGW_TARGET_ENV:-"${CONTRACT_ROOT}/rgw-artifact-target.env"}
RGW_ENDPOINT_DEFAULT=${RGW_ENDPOINT_DEFAULT:-http://192.168.3.171:7480}
RGW_BUCKET_DEFAULT=${RGW_BUCKET_DEFAULT:-darwin-hpc-artifacts}
RGW_UID_DEFAULT=${RGW_UID_DEFAULT:-darwin-hpc-artifact-publisher}
RGW_VELERO_BUCKET_DEFAULT=${RGW_VELERO_BUCKET_DEFAULT:-darwin-k8s-backups}
PUBLICATION_TARGET_ID_DEFAULT=${PUBLICATION_TARGET_ID_DEFAULT:-hpc-artifacts-v1}
GATEWAY_NAMESPACE=${GATEWAY_NAMESPACE:-darwin-platform}
GATEWAY_SERVICE=${GATEWAY_SERVICE:-darwin-hpc-gateway}
LOCAL_PORT=${LOCAL_PORT:-18102}
POLL_INTERVAL_SECONDS=${POLL_INTERVAL_SECONDS:-2}
POLL_TIMEOUT_SECONDS=${POLL_TIMEOUT_SECONDS:-240}

readonly SCRIPT_DIR REPO_ROOT DOC_ROOT CONTRACT_ROOT ARTIFACT_ROOT PHASE_ROOT RESULT_DIR RGW_TARGET_ENV

require_cmd() {
  local cmd=$1
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "missing required command: ${cmd}" >&2
    exit 1
  fi
}

ensure_python_dep() {
  if python3 - <<'PY' >/dev/null 2>&1
import importlib.util
import sys
sys.exit(0 if importlib.util.find_spec("boto3") and importlib.util.find_spec("botocore") else 1)
PY
  then
    return 0
  fi

  export DEBIAN_FRONTEND=noninteractive
  apt-get install -y python3-boto3 python3-botocore >/dev/null
}

ensure_green_cluster() {
  local node
  for node in t560-proxmox r770-proxmox 5860-proxmox; do
    local ready
    ready=$(kubectl get node "${node}" -o jsonpath='{range .status.conditions[?(@.type=="Ready")]}{.status}{end}')
    [[ "${ready}" == "True" ]] || {
      echo "node not Ready: ${node}" >&2
      exit 1
    }
  done

  local coredns_ready
  coredns_ready=$(kubectl -n kube-system get deploy coredns -o jsonpath='{.status.readyReplicas}/{.status.replicas}' 2>/dev/null || true)
  [[ "${coredns_ready%%/*}" == "${coredns_ready##*/}" ]] || {
    echo "CoreDNS not fully ready: ${coredns_ready}" >&2
    exit 1
  }
}

materialize_rgw_target() {
  local user_json
  local access_key
  local secret_key

  user_json=$(radosgw-admin user info --uid="${RGW_UID_DEFAULT}" 2>/dev/null || true)
  if [[ -z "${user_json}" ]]; then
    user_json=$(radosgw-admin user create \
      --uid="${RGW_UID_DEFAULT}" \
      --display-name="Darwin HPC Artifact Publisher")
  fi

  access_key=$(python3 - <<'PY' "${user_json}"
import json
import sys
print(json.loads(sys.argv[1])["keys"][0]["access_key"])
PY
)
  secret_key=$(python3 - <<'PY' "${user_json}"
import json
import sys
print(json.loads(sys.argv[1])["keys"][0]["secret_key"])
PY
)

  cat > "${RGW_TARGET_ENV}" <<EOF
# B10 object target contract
# generated by run_object_artifact_matrix.sh
RGW_ENDPOINT=${RGW_ENDPOINT_DEFAULT}
RGW_BUCKET=${RGW_BUCKET_DEFAULT}
RGW_UID=${RGW_UID_DEFAULT}
RGW_VELERO_BUCKET=${RGW_VELERO_BUCKET_DEFAULT}
PUBLICATION_TARGET_ID=${PUBLICATION_TARGET_ID_DEFAULT}
RGW_ACCESS_KEY=${access_key}
RGW_SECRET_KEY=${secret_key}
EOF
  chmod 0600 "${RGW_TARGET_ENV}"
}

submit_profile() {
  local profile_id=$1
  local prefix=$2
  local run_label=$3
  local request_file="${RESULT_DIR}/${prefix}-request.json"
  local submit_file="${RESULT_DIR}/${prefix}-submit.txt"
  local status_file="${RESULT_DIR}/${prefix}-status.txt"
  local source_artifact_file="${RESULT_DIR}/${prefix}-source-artifact.txt"
  local source_stdout_file="${RESULT_DIR}/${prefix}-source-stdout.txt"
  local source_stderr_file="${RESULT_DIR}/${prefix}-source-stderr.txt"
  local job_id
  local state
  local start_epoch

  cat > "${request_file}" <<EOF
{"profile_id":"${profile_id}","parameters":{"run_label":"${run_label}"}}
EOF

  curl -fsS -X POST \
    -H 'Content-Type: application/json' \
    --data @"${request_file}" \
    "http://127.0.0.1:${LOCAL_PORT}/jobs/submit" \
    > "${submit_file}"

  job_id=$(jq -r '.job_id' "${submit_file}")
  [[ -n "${job_id}" && "${job_id}" != "null" ]] || {
    echo "missing job id for ${profile_id}" >&2
    exit 1
  }

  start_epoch=$(date +%s)
  while true; do
    curl -fsS "http://127.0.0.1:${LOCAL_PORT}/jobs/${job_id}" > "${status_file}"
    state=$(jq -r '.state' "${status_file}")
    if [[ "${state}" =~ ^(COMPLETED|FAILED|CANCELLED|TIMEOUT)$ ]]; then
      break
    fi
    if (( $(date +%s) - start_epoch >= POLL_TIMEOUT_SECONDS )); then
      echo "timeout waiting for ${profile_id} to reach terminal state" >&2
      exit 1
    fi
    sleep "${POLL_INTERVAL_SECONDS}"
  done

  [[ "${state}" == "COMPLETED" ]] || {
    echo "${profile_id} ended in state ${state}" >&2
    exit 1
  }

  curl -fsS "http://127.0.0.1:${LOCAL_PORT}/jobs/${job_id}/artifact-manifest" > "${source_artifact_file}"
  curl -fsS "http://127.0.0.1:${LOCAL_PORT}/jobs/${job_id}/stdout" > "${source_stdout_file}"
  curl -fsS "http://127.0.0.1:${LOCAL_PORT}/jobs/${job_id}/stderr" > "${source_stderr_file}"
}

publish_source_manifest() {
  local prefix=$1
  local source_manifest_file="${RESULT_DIR}/${prefix}-source-artifact.txt"
  local output_manifest_file="${RESULT_DIR}/${prefix}-object-manifest.json"
  local output_head_file="${RESULT_DIR}/${prefix}-object-head.txt"

  SOURCE_MANIFEST_FILE="${source_manifest_file}" \
  OUTPUT_MANIFEST_FILE="${output_manifest_file}" \
  OUTPUT_HEAD_FILE="${output_head_file}" \
  PUBLICATION_RUN_ID="${RUN_ID}" \
  python3 - <<'PY'
import base64
import hashlib
import json
import mimetypes
import os
import shlex
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import boto3
import botocore.exceptions

source_manifest_file = Path(os.environ["SOURCE_MANIFEST_FILE"])
output_manifest_file = Path(os.environ["OUTPUT_MANIFEST_FILE"])
output_head_file = Path(os.environ["OUTPUT_HEAD_FILE"])
source = json.loads(source_manifest_file.read_text())

profile_id = source["profile_id"]
job_id = int(source["job_id"])
run_label = source["run_label"]
node_name = source.get("node_list", "")
bucket = os.environ["RGW_BUCKET"]
endpoint = os.environ["RGW_ENDPOINT"]
publication_target_id = os.environ["PUBLICATION_TARGET_ID"]

def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()

def read_bytes(path_str: str, node: str) -> bytes:
    path = Path(path_str)
    if path.exists():
        return path.read_bytes()
    code = "import base64, pathlib, sys; print(base64.b64encode(pathlib.Path(sys.argv[1]).read_bytes()).decode())"
    remote_cmd = f"python3 -c {shlex.quote(code)} {shlex.quote(path_str)}"
    data_b64 = subprocess.check_output(
        [
            "ssh",
            "-o",
            "BatchMode=yes",
            "-o",
            "StrictHostKeyChecking=accept-new",
            f"root@{node}",
            remote_cmd,
        ],
        text=True,
    )
    return base64.b64decode(data_b64.strip())

artifact_bytes = read_bytes(source["artifact_path"], node_name)
stdout_bytes = read_bytes(source["stdout_path"], node_name)
stderr_bytes = read_bytes(source["stderr_path"], node_name)

base_prefix = f"hpc/{profile_id}/{job_id}/{run_label}"
artifact_key = f"{base_prefix}/artifact.bin"
stdout_key = f"{base_prefix}/stdout.txt"
stderr_key = f"{base_prefix}/stderr.txt"
manifest_key = f"{base_prefix}/artifact-manifest.json"
publication_time = datetime.now(timezone.utc).astimezone().isoformat()

entries = [
    {
        "artifact_kind": "artifact",
        "local_bytes": artifact_bytes,
        "object_key": artifact_key,
        "content_type": source.get("artifact_mime_type") or mimetypes.guess_type("artifact.bin")[0] or "application/octet-stream",
        "published_checksum": sha256_bytes(artifact_bytes),
        "size_bytes": len(artifact_bytes),
    },
    {
        "artifact_kind": "stdout",
        "local_bytes": stdout_bytes,
        "object_key": stdout_key,
        "content_type": "text/plain; charset=utf-8",
        "published_checksum": sha256_bytes(stdout_bytes),
        "size_bytes": len(stdout_bytes),
    },
    {
        "artifact_kind": "stderr",
        "local_bytes": stderr_bytes,
        "object_key": stderr_key,
        "content_type": "text/plain; charset=utf-8",
        "published_checksum": sha256_bytes(stderr_bytes),
        "size_bytes": len(stderr_bytes),
    },
]

artifact_entry = next(entry for entry in entries if entry["artifact_kind"] == "artifact")
manifest = {
    "manifest_format": "darwin-b101-object-artifact-v1",
    "publication_target_id": publication_target_id,
    "source_phase": "B10.2",
    "source_run_id": os.environ["PUBLICATION_RUN_ID"],
    "source_manifest_path": str(source_manifest_file),
    "job_id": job_id,
    "job_name": source["job_name"],
    "profile_id": profile_id,
    "run_label": run_label,
    "state": source["state"],
    "submit_time": source["submit_time"],
    "start_time": source["start_time"],
    "end_time": source["end_time"],
    "exit_code": source["exit_code"],
    "object_bucket": bucket,
    "object_key": artifact_key,
    "manifest_object_key": manifest_key,
    "publication_time": publication_time,
    "published_checksum": artifact_entry["published_checksum"],
    "published_objects": [
        {
            "artifact_kind": entry["artifact_kind"],
            "object_key": entry["object_key"],
            "content_type": entry["content_type"],
            "published_checksum": entry["published_checksum"],
            "size_bytes": entry["size_bytes"],
        }
        for entry in entries
    ],
}

output_manifest_file.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
manifest_bytes = output_manifest_file.read_bytes()
manifest_entry = {
    "artifact_kind": "manifest",
    "local_bytes": manifest_bytes,
    "object_key": manifest_key,
    "content_type": "application/json",
    "published_checksum": sha256_bytes(manifest_bytes),
    "size_bytes": len(manifest_bytes),
}
all_entries = entries + [manifest_entry]

s3 = boto3.client(
    "s3",
    endpoint_url=endpoint,
    aws_access_key_id=os.environ["RGW_ACCESS_KEY"],
    aws_secret_access_key=os.environ["RGW_SECRET_KEY"],
    region_name="us-east-1",
)

try:
    s3.head_bucket(Bucket=bucket)
except botocore.exceptions.ClientError as exc:
    code = exc.response.get("Error", {}).get("Code", "")
    if code in {"404", "NoSuchBucket", "NotFound"}:
        s3.create_bucket(Bucket=bucket)
    else:
        raise

for entry in all_entries:
    s3.put_object(
        Bucket=bucket,
        Key=entry["object_key"],
        Body=entry["local_bytes"],
        ContentType=entry["content_type"],
        Metadata={
            "sha256": entry["published_checksum"],
            "job-id": str(job_id),
            "profile-id": profile_id,
            "run-label": run_label,
            "artifact-kind": entry["artifact_kind"],
        },
    )

head_records = []
for entry in all_entries:
    head = s3.head_object(Bucket=bucket, Key=entry["object_key"])
    remote_body = s3.get_object(Bucket=bucket, Key=entry["object_key"])["Body"].read()
    remote_sha = sha256_bytes(remote_body)
    if remote_sha != entry["published_checksum"]:
        raise SystemExit(f"checksum mismatch for {entry['object_key']}: local={entry['published_checksum']} remote={remote_sha}")
    head_records.append(
        {
            "artifact_kind": entry["artifact_kind"],
            "object_bucket": bucket,
            "object_key": entry["object_key"],
            "content_length": head["ContentLength"],
            "content_type": head.get("ContentType", ""),
            "etag": head.get("ETag", ""),
            "metadata": head.get("Metadata", {}),
            "verified_checksum": remote_sha,
        }
    )

output_head_file.write_text(json.dumps(head_records, indent=2, sort_keys=True) + "\n", encoding="utf-8")
PY
}

collect_final_health() {
  {
    echo "captured_at=$(date -Iseconds)"
    echo
    echo "## kubernetes-nodes"
    kubectl get nodes -o wide || true
    echo
    if command -v cilium >/dev/null 2>&1; then
      echo "## cilium"
      cilium status --wait --wait-duration=30s || true
      echo
    fi
    echo "## coredns"
    kubectl -n kube-system get deploy coredns || true
    echo
    echo "## slurm-units"
    for unit in slurmctld slurmrestd munge; do
      printf '%s=%s\n' "${unit}" "$(systemctl is-active "${unit}" 2>/dev/null || true)"
    done
    echo
    if command -v scontrol >/dev/null 2>&1; then
      echo "## scontrol-ping"
      scontrol ping || true
      echo
    fi
    if command -v sinfo >/dev/null 2>&1; then
      echo "## slurm-sinfo"
      sinfo -N -l || true
      echo
    fi
  } > "${RESULT_DIR}/final-cluster-health.txt"
}

write_result() {
  python3 - <<'PY' "${RESULT_DIR}/cpu-batch-object-manifest.json" "${RESULT_DIR}/gpu-object-manifest.json" "${RESULT_DIR}/B102_RESULT.md" "${RUN_ID}"
import json
import pathlib
import sys

cpu = json.loads(pathlib.Path(sys.argv[1]).read_text())
gpu = json.loads(pathlib.Path(sys.argv[2]).read_text())
out = pathlib.Path(sys.argv[3])
run_id = sys.argv[4]

out.write_text(
    "# B10.2 Multi-profile Object Publication Result\n\n"
    "## Status\n"
    "GO\n\n"
    "## Decision\n"
    "the object result plane generalized cleanly across cpu-batch-v1 and gpu-single-v1 using the same bucket family, deterministic keying, and remote checksum validation.\n\n"
    "## Profiles\n"
    f"- cpu-batch-v1: job_id={cpu['job_id']}, object_key={cpu['object_key']}\n"
    f"- gpu-single-v1: job_id={gpu['job_id']}, object_key={gpu['object_key']}\n"
    f"\n## Canonical Run\n- run id: {run_id}\n",
    encoding="utf-8",
)
PY
}

main() {
  require_cmd jq
  require_cmd kubectl
  require_cmd python3
  require_cmd curl
  require_cmd ssh
  require_cmd radosgw-admin

  if [[ -z "${KUBECONFIG:-}" && -f /etc/kubernetes/admin.conf ]]; then
    export KUBECONFIG=/etc/kubernetes/admin.conf
  fi

  mkdir -p "${RESULT_DIR}"
  exec > >(tee "${RESULT_DIR}/publish-log.txt") 2>&1

  ensure_green_cluster
  ensure_python_dep
  materialize_rgw_target
  source "${RGW_TARGET_ENV}"
  export RGW_ENDPOINT RGW_BUCKET RGW_ACCESS_KEY RGW_SECRET_KEY PUBLICATION_TARGET_ID

  [[ "${RGW_BUCKET}" != "${RGW_VELERO_BUCKET}" ]] || {
    echo "artifact bucket must not match Velero bucket" >&2
    exit 1
  }

  kubectl -n "${GATEWAY_NAMESPACE}" port-forward "service/${GATEWAY_SERVICE}" "${LOCAL_PORT}:80" > "${RESULT_DIR}/port-forward.log" 2>&1 &
  PF_PID=$!
  cleanup() {
    kill "${PF_PID}" >/dev/null 2>&1 || true
  }
  trap cleanup EXIT
  for _ in $(seq 1 20); do
    if curl -fsS "http://127.0.0.1:${LOCAL_PORT}/profiles" > "${RESULT_DIR}/profiles-response.json"; then
      break
    fi
    sleep 1
  done
  [[ -s "${RESULT_DIR}/profiles-response.json" ]] || {
    echo "gateway /profiles did not become ready through port-forward" >&2
    exit 1
  }

  submit_profile "cpu-batch-v1" "cpu-batch" "b102-${RUN_ID}-cpu-batch"
  submit_profile "gpu-single-v1" "gpu" "b102-${RUN_ID}-gpu-single"

  publish_source_manifest "cpu-batch"
  publish_source_manifest "gpu"

  collect_final_health
  write_result
  echo "B10.2 object artifact matrix artifacts written to ${RESULT_DIR}"
}

main "$@"
