apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-ai-runtime-r770-pv
spec:
  capacity:
    storage: 140Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-ai-runtime-r770
  local:
    path: /mnt/ai-runtime/k8s-local-runtime-cache
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - r770-proxmox
