use crate::domain::Domain;
use once_cell::sync::Lazy;
use std::collections::HashMap;

/// Keywords expandidos por domínio, incluindo especialidades Darwin
pub static DOMAIN_KEYWORDS: Lazy<HashMap<Domain, Vec<&'static str>>> = Lazy::new(|| {
    let mut map = HashMap::new();

    // === Medical Sciences ===
    map.insert(
        Domain::PBPK,
        vec![
            "farmacocinética",
            "pbpk",
            "clearance",
            "volume de distribuição",
            "meia-vida",
            "biodisponibilidade",
            "absorção",
            "eliminação",
            "metabolismo",
            "compartimento",
            "modelo compartimental",
            "concentração plasmática",
            "dose",
            "posologia",
            "pk/pd",
            "farmacodinâmica",
            "auc",
            "cmax",
            "tmax",
            "cyp450",
            "indução enzimática",
            "inibição enzimática",
        ],
    );

    map.insert(
        Domain::ClinicalMedicine,
        vec![
            "diagnóstico",
            "diagnóstico diferencial",
            "paciente",
            "sintoma",
            "síndrome",
            "patologia",
            "clínica",
            "terapêutica",
            "prognóstico",
            "exame físico",
            "anamnese",
            "história clínica",
            "inspeção",
            "palpação",
            "percussão",
            "ausculta",
            "semiologia",
            "propedêutica",
            "medicina interna",
            "comorbidade",
            "epidemiologia",
            "prevalência",
            "incidência",
            "rastreamento",
            "prevenção",
            "hipertensão",
            "diabetes",
            "insuficiência cardíaca",
            "pneumonia",
            "sepse",
            "choque",
            "eletrocardiograma",
            "radiografia",
            "tomografia",
            "ultrassom",
        ],
    );

    map.insert(
        Domain::Psychiatry,
        vec![
            "psiquiatria",
            "psicofármaco",
            "antidepressivo",
            "antipsicótico",
            "estabilizador de humor",
            "ansiolítico",
            "benzodiazepínico",
            "depressão",
            "transtorno bipolar",
            "mania",
            "hipomania",
            "esquizofrenia",
            "psicose",
            "delírio",
            "alucinação",
            "transtorno de ansiedade",
            "tag",
            "toc",
            "tept",
            "tdah",
            "autismo",
            "transtorno de personalidade",
            "ssri",
            "snri",
            "imao",
            "tricíclico",
            "risperidona",
            "olanzapina",
            "quetiapina",
            "aripiprazol",
            "lítio",
            "valproato",
            "carbamazepina",
            "lamotrigina",
        ],
    );

    map.insert(
        Domain::Neuroscience,
        vec![
            "neurônio",
            "sinapse",
            "neurotransmissor",
            "dopamina",
            "serotonina",
            "gaba",
            "glutamato",
            "córtex",
            "hipocampo",
            "amígdala",
            "tálamo",
            "cerebelo",
            "plasticidade neural",
            "potencial de ação",
            "receptor",
            "canal iônico",
            "neuroimagem",
            "fmri",
            "eeg",
            "meg",
            "tratos neurais",
            "conectoma",
        ],
    );

    // === Exact Sciences ===
    map.insert(
        Domain::Physics,
        vec![
            "mecânica",
            "newton",
            "lagrangiana",
            "hamiltoniana",
            "força",
            "energia",
            "momento",
            "eletromagnetismo",
            "maxwell",
            "onda eletromagnética",
            "relatividade",
            "espaço-tempo",
            "gravidade",
            "termodinâmica",
            "entropia",
            "temperatura",
            "ótica",
            "refração",
            "difração",
            "interferência",
            "modelo padrão",
            "partícula",
            "experimento de dupla fenda",
        ],
    );

    map.insert(
        Domain::Quantum,
        vec![
            "quântico",
            "quantum",
            "mecânica quântica",
            "schrödinger",
            "função de onda",
            "operador",
            "superposição",
            "emaranhamento",
            "entrelaçamento",
            "spin",
            "momento angular quântico",
            "orbital",
            "átomo",
            "heisenberg",
            "incerteza",
            "colapso",
            "medida quântica",
            "observável",
            "hamiltoniano",
            "autovalor",
            "bra",
            "ket",
            "notação de dirac",
        ],
    );

    map.insert(
        Domain::Chemistry,
        vec![
            "química",
            "reação",
            "síntese",
            "mecanismo",
            "orbital molecular",
            "ligação química",
            "estequiometria",
            "concentração molar",
            "ph",
            "ácido",
            "base",
            "titulação",
            "cromatografia",
            "espectroscopia",
            "ftir",
            "nmr",
            "ressonância magnética nuclear",
            "orgânica",
            "inorgânica",
            "analítica",
            "nomenclatura iupac",
            "isômero",
        ],
    );

    // === Interdisciplinary ===
    map.insert(
        Domain::Biomaterials,
        vec![
            "biomaterial",
            "scaffold",
            "biocompatibilidade",
            "engenharia de tecidos",
            "tissue engineering",
            "citotoxicidade",
            "bioabsorção",
            "biodegradação",
            "nanomedicina",
            "nanopartícula",
            "drug delivery",
            "eletrofiação",
            "electrospinning",
            "impressão 3d",
            "sem",
            "microscopia eletrônica",
            "polímero",
            "hidrogel",
            "nanofibra",
            "regeneração tecidual",
            "medicina regenerativa",
        ],
    );

    map.insert(
        Domain::Heliobiology,
        vec![
            "heliobiologia",
            "cronobiologia",
            "ritmo circadiano",
            "relógio biológico",
            "clock gene",
            "melatonina",
            "ciclo sono-vigília",
            "zeitgeber",
            "sincronização temporal",
            "cronotipo",
            "jet lag",
            "trabalho em turnos",
            "núcleo supraquiasmático",
            "per",
            "cry",
            "bmal1",
            "clock",
            "cronofarmacologia",
            "fotobiologia",
        ],
    );

    map.insert(
        Domain::ComplexSystems,
        vec![
            "sistemas complexos",
            "complexidade",
            "caos",
            "teoria do caos",
            "atrator estranho",
            "fractal",
            "dimensão fractal",
            "emergência",
            "auto-organização",
            "dinâmica não-linear",
            "bifurcação",
            "criticalidade",
            "rede complexa",
            "scale-free",
            "small-world",
            "entropia",
            "teoria da informação",
            "sensibilidade às condições iniciais",
            "sistema adaptativo complexo",
        ],
    );

    // === Philosophy & Meta ===
    map.insert(
        Domain::Philosophy,
        vec![
            "consciência",
            "qualia",
            "fenomenologia",
            "ontologia",
            "epistemologia",
            "metafísica",
            "dialética",
            "transcendental",
            "imanente",
            "ser-aí",
            "dasein",
            "intencionalidade",
            "subjetividade",
            "husserl",
            "heidegger",
            "kant",
            "spinoza",
            "entropia simbólica",
        ],
    );

    map.insert(
        Domain::Q1Scholar,
        vec![
            "q1",
            "quartil 1",
            "fator de impacto",
            "impacto",
            "revisão por pares",
            "peer review",
            "publicação científica",
            "artigo científico",
            "nature",
            "science",
            "cell",
            "lancet",
            "metodologia científica",
            "estatística inferencial",
            "p-valor",
            "intervalo de confiança",
            "reprodutibilidade",
            "manuscrito",
            "submission",
            "revista indexada",
        ],
    );

    map.insert(
        Domain::MetaDiscovery,
        vec![
            "meta-análise",
            "revisão sistemática",
            "metodologia de pesquisa",
            "design experimental",
            "epistemologia científica",
            "filosofia da ciência",
            "paradigma",
            "kuhn",
            "revolução científica",
            "descoberta científica",
            "serendipidade",
            "heurística",
            "criatividade científica",
            "open science",
            "reprodutibilidade",
            "ciência da ciência",
        ],
    );

    map.insert(
        Domain::Discovery,
        vec![
            "exploratório",
            "pesquisa exploratória",
            "descoberta",
            "investigação",
            "hipótese",
            "experimento piloto",
            "prova de conceito",
            "screening",
            "rastreamento",
            "data mining",
            "análise exploratória",
            "alto rendimento",
            "high-throughput",
            "serendipidade",
        ],
    );

    // === Engineering ===
    map.insert(
        Domain::BeagleEngine,
        vec![
            "rust",
            "axum",
            "tokio",
            "async",
            "trait",
            "lifetime",
            "beagle",
            "hypergraph",
            "vertex ai",
            "anthropic",
            "postgresql",
            "redis",
            "qdrant",
            "neo4j",
            "cargo",
            "workspace",
            "crate",
            "impl",
            "struct",
            "refatoração",
            "otimização",
            "performance",
            "latência",
            "memory leak",
            "borrow checker",
            "ownership",
        ],
    );

    map.insert(
        Domain::ChemicalEngineering,
        vec![
            "engenharia química",
            "reator químico",
            "operação unitária",
            "balanço de massa",
            "balanço de energia",
            "destilação",
            "cristalização",
            "extração",
            "transferência de calor",
            "transferência de massa",
            "processo químico",
            "cinética de reação",
        ],
    );

    // === Law & Arts ===
    map.insert(
        Domain::MedicalLaw,
        vec![
            "bioética",
            "consentimento informado",
            "autonomia",
            "confidencialidade",
            "prontuário",
            "erro médico",
            "responsabilidade civil",
            "iatrogenia",
            "imperícia",
            "negligência",
            "imprudência",
            "código de ética",
            "conselho regional",
            "crm",
            "anvisa",
            "regulação sanitária",
        ],
    );

    map.insert(
        Domain::Music,
        vec![
            "harmonia",
            "contraponto",
            "fuga",
            "tonalidade",
            "modulação",
            "acorde",
            "escala",
            "modo",
            "cadência",
            "sinfonia",
            "sonata",
            "concerto",
            "quarteto",
            "bach",
            "beethoven",
            "mahler",
            "schoenberg",
            "atonalismo",
            "serialismo",
            "tempo",
            "ritmo",
            "métrica",
            "dinâmica",
        ],
    );

    map
});
