apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moshi-hf-cache
  namespace: moshi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  storageClassName: ceph-rbd-ssd
