apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orangefs-ceph-scratch-bench
  namespace: beagle
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-ssd-scratch
  resources:
    requests:
      storage: 20Gi

