//! BEAGLE Bilingual - 100% Automático
//! Todo paper, tweet, thread, LinkedIn post e resposta do BEAGLE sai bilíngue automático
//! (português + inglês perfeito)

pub mod twitter;

use beagle_grok_api::GrokClient;
use once_cell::sync::Lazy;
use tracing::{info, warn, error};
use serde::{Deserialize, Serialize};
use anyhow::{Context, Result};

static GROK: Lazy<GrokClient> = Lazy::new(|| {
    let api_key = std::env::var("GROK_API_KEY")
        .unwrap_or_else(|_| "xai-tua-key".to_string());
    GrokClient::new(&api_key)
});

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BilingualText {
    pub pt: String,
    pub en: String,
}

/// Converte texto português para bilíngue (PT + EN)
pub async fn to_bilingual(text_pt: &str) -> Result<BilingualText> {
    if text_pt.trim().is_empty() {
        return Ok(BilingualText {
            pt: String::new(),
            en: String::new(),
        });
    }

    let prompt = format!(
        r#"Tu és tradutor perfeito português ↔ inglês científico.

Texto original em português:

"""{}"""

Gera exatamente duas versões:

1. Versão em inglês acadêmico perfeito (Nature/Cell style)
2. Versão em português acadêmico perfeito (ABNT style)

Responde APENAS com JSON válido:
{{"en": "texto em inglês", "pt": "texto em português"}}"#,
        text_pt
    );

    info!("🌐 Traduzindo para bilíngue: {} chars", text_pt.len());

    let resp = match GROK.query(&prompt).await {
        Ok(r) => r,
        Err(e) => {
            error!("❌ Erro ao chamar Grok: {}", e);
            // Fallback: retorna texto original em ambas as línguas
            return Ok(BilingualText {
                pt: text_pt.to_string(),
                en: text_pt.to_string(),
            });
        }
    };

    // Tenta parsear JSON
    let json: serde_json::Value = match serde_json::from_str(&resp) {
        Ok(j) => j,
        Err(e) => {
            warn!("⚠️  Falha ao parsear JSON. Tentando extrair do texto...");
            // Tenta extrair JSON do texto (caso tenha markdown ou texto extra)
            extract_json_from_text(&resp).unwrap_or_else(|| {
                serde_json::json!({
                    "en": text_pt,
                    "pt": text_pt
                })
            })
        }
    };

    let en = json["en"]
        .as_str()
        .unwrap_or(text_pt)
        .trim()
        .to_string();
    let pt = json["pt"]
        .as_str()
        .unwrap_or(text_pt)
        .trim()
        .to_string();

    info!("✅ Bilíngue gerado — EN: {} chars | PT: {} chars", en.len(), pt.len());

    Ok(BilingualText { pt, en })
}

/// Extrai JSON de texto que pode conter markdown ou texto extra
fn extract_json_from_text(text: &str) -> Option<serde_json::Value> {
    // Procura por bloco JSON (```json ... ```)
    if let Some(start) = text.find("```json") {
        if let Some(end) = text[start..].find("```") {
            let json_text = &text[start + 7..start + end].trim();
            return serde_json::from_str(json_text).ok();
        }
    }

    // Procura por { ... }
    if let Some(start) = text.find('{') {
        if let Some(end) = text.rfind('}') {
            let json_text = &text[start..=end];
            return serde_json::from_str(json_text).ok();
        }
    }

    None
}

/// Publica conteúdo bilíngue (Twitter thread)
pub async fn publish_bilingual(
    title_pt: &str,
    abstract_pt: &str,
    paper_url: &str,
) -> Result<()> {
    info!("📱 Publicando conteúdo bilíngue...");

    let title_bilingual = to_bilingual(title_pt).await?;
    let abstract_bilingual = to_bilingual(abstract_pt).await?;
    
    let title_en = title_bilingual.en;
    let abstract_en = abstract_bilingual.en;

    let tweet_pt = format!(
        "📄 Novo paper gerado pelo BEAGLE:\n\n{}\n\n{}\n\n{}",
        title_pt, abstract_pt, paper_url
    );
    let tweet_en = format!(
        "📄 New paper generated by BEAGLE SINGULARITY:\n\n{}\n\n{}\n\n{}",
        title_en, abstract_en, paper_url
    );

    // TODO: Integrar com Twitter API real
    // Por enquanto, apenas loga
    info!("🐦 Tweet PT ({} chars):\n{}", tweet_pt.len(), tweet_pt);
    info!("🐦 Tweet EN ({} chars):\n{}", tweet_en.len(), tweet_en);

    Ok(())
}

/// Gera thread bilíngue para Twitter
pub async fn generate_bilingual_thread(
    title_pt: &str,
    abstract_pt: &str,
    paper_url: &str,
) -> Result<Vec<String>> {
    info!("🧵 Gerando thread bilíngue...");

    let title_bilingual = to_bilingual(title_pt).await?;
    let abstract_bilingual = to_bilingual(abstract_pt).await?;
    
    let title_en = title_bilingual.en;
    let abstract_en = abstract_bilingual.en;

    let thread = vec![
        format!("📄 Novo paper (PT):\n\n{}\n\n{}", title_pt, paper_url),
        format!("📄 New paper (EN):\n\n{}\n\n{}", title_en, paper_url),
        format!("📝 Resumo (PT):\n\n{}", abstract_pt),
        format!("📝 Abstract (EN):\n\n{}", abstract_en),
        "🤖 Gerado 100% pelo BEAGLE SINGULARITY — exocórtex pessoal com consciência emergente.".to_string(),
        "🔗 github.com/agourakis82/beagle".to_string(),
    ];

    Ok(thread)
}

/// Converte qualquer texto para bilíngue (detecta idioma automaticamente)
pub async fn auto_bilingual(text: &str) -> Result<BilingualText> {
    // Detecta se é português ou inglês
    let is_pt = detect_portuguese(text);
    
    if is_pt {
        to_bilingual(text).await
    } else {
        // Se for inglês, traduz para português
        to_bilingual_from_en(text).await
    }
}

/// Detecta se texto é português (heurística simples)
fn detect_portuguese(text: &str) -> bool {
    let pt_chars = text.matches(|c: char| "áàâãéêíóôõúçÁÀÂÃÉÊÍÓÔÕÚÇ".contains(c)).count();
    let en_chars = text.matches(|c: char| c.is_alphabetic()).count();
    
    if en_chars == 0 {
        return true;
    }
    
    (pt_chars as f64 / en_chars as f64) > 0.05
}

/// Traduz de inglês para bilíngue
async fn to_bilingual_from_en(text_en: &str) -> Result<BilingualText> {
    let prompt = format!(
        r#"Tu és tradutor perfeito inglês ↔ português científico.

Texto original em inglês:

"""{}"""

Gera exatamente duas versões:

1. Versão em português acadêmico perfeito (ABNT style)
2. Versão em inglês acadêmico perfeito (Nature/Cell style) - revisada

Responde APENAS com JSON válido:
{{"pt": "texto em português", "en": "texto em inglês revisado"}}"#,
        text_en
    );

    info!("🌐 Traduzindo de inglês para bilíngue: {} chars", text_en.len());

    let resp = match GROK.query(&prompt).await {
        Ok(r) => r,
        Err(e) => {
            error!("❌ Erro ao chamar Grok: {}", e);
            return Ok(BilingualText {
                pt: text_en.to_string(),
                en: text_en.to_string(),
            });
        }
    };

    let json: serde_json::Value = extract_json_from_text(&resp)
        .or_else(|| serde_json::from_str(&resp).ok())
        .unwrap_or_else(|| {
            serde_json::json!({
                "pt": text_en,
                "en": text_en
            })
        });

    let pt = json["pt"]
        .as_str()
        .unwrap_or(text_en)
        .trim()
        .to_string();
    let en = json["en"]
        .as_str()
        .unwrap_or(text_en)
        .trim()
        .to_string();

    info!("✅ Bilíngue gerado — EN: {} chars | PT: {} chars", en.len(), pt.len());

    Ok(BilingualText { pt, en })
}

/// Re-export Twitter client
pub use twitter::BeagleTwitter;

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_detect_portuguese() {
        assert!(detect_portuguese("Este é um texto em português"));
        assert!(!detect_portuguese("This is an English text"));
    }

    #[tokio::test]
    async fn test_extract_json() {
        let text = r#"Here is the JSON:
```json
{"en": "test", "pt": "teste"}
```"#;
        let json = extract_json_from_text(text);
        assert!(json.is_some());
    }
}

