server = "http://192.168.3.207:5003"

[host."http://10.100.100.3:5003"]
  capabilities = ["pull", "resolve"]
  skip_verify = true

[host."http://192.168.3.207:5003"]
  capabilities = ["pull", "resolve"]
  skip_verify = true
