interface=vmbr30
bind-interfaces
listen-address=10.30.0.1
domain=svc10g.lab.sounio
expand-hosts
domain-needed
bogus-priv
dhcp-authoritative
dhcp-range=10.30.0.100,10.30.0.199,255.255.255.0,12h
dhcp-option=option:router,10.30.0.1
dhcp-option=option:dns-server,10.30.0.1
address=/registry.svc10g.lab.sounio/10.30.0.1
address=/push-registry.svc10g.lab.sounio/10.30.0.1
address=/dns.svc10g.lab.sounio/10.30.0.1
address=/ipam.svc10g.lab.sounio/10.30.0.1
address=/netbox.svc10g.lab.sounio/10.30.0.1
address=/registry.lab.sounio/192.168.3.207
address=/push-registry.lab.sounio/192.168.3.207
address=/dnsctrl.lab.sounio/192.168.3.207
address=/ipam.lab.sounio/192.168.3.207
address=/netbox.lab.sounio/192.168.3.207
server=192.168.3.1
server=/lab.sounio/10.96.80.85
