apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-cockpit-data
  namespace: beagle
  labels:
    app.kubernetes.io/name: project-cockpit
    app.kubernetes.io/part-of: beagle
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd-ssd
  resources:
    requests:
      storage: 20Gi
