apiVersion: v1
kind: ServiceAccount
metadata:
  name: project-cockpit
  namespace: beagle
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: project-cockpit
  namespace: beagle
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["beagle-core-secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["statefulsets/scale"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-cockpit
  namespace: beagle
subjects:
  - kind: ServiceAccount
    name: project-cockpit
    namespace: beagle
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: project-cockpit
