apiVersion: v1
kind: Service
metadata:
  name: gpu-chat
  namespace: beagle
  labels:
    app.kubernetes.io/name: gpu-chat
    app.kubernetes.io/part-of: beagle
spec:
  selector:
    app: gpu-chat
  ports:
    - port: 8090
      targetPort: 8090
