apiVersion: v1
kind: Service
metadata:
  name: beagle-workspace
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: beagle-workspace
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: ssh
      port: 2222
      targetPort: ssh
