apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: beagle
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - sovereign-embeddings-deployment.yaml
  - sovereign-embeddings-service.yaml
  - sovereign-reranker-deployment.yaml
  - sovereign-reranker-service.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: beagle
