apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beagle-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  storageClassName: ceph-rbd-ssd
