apiVersion: v1
kind: Service
metadata:
  name: beagle-core
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: beagle-core
  ports:
    - name: http
      port: 8080
      targetPort: http
