apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cpu-batch-job.yaml
  - cpu-standard-job.yaml
  - gpu-batch-job.yaml
  - runtimeclass-nvidia.yaml
  - nvidia-device-plugin-daemonset.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: beagle
