apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-zfast-t560-beagle-workspace-pv
spec:
  capacity:
    storage: 120Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-zfast-t560
  local:
    path: /zfast/workspaces/live/beagle-workspace
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - t560-proxmox
