apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beagle-core-local-data
  namespace: beagle
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-zfast-t560
  volumeName: local-zfast-t560-beagle-core-pv
  resources:
    requests:
      storage: 20Gi
