apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-zfast-t560
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
