apiVersion: v1
kind: ConfigMap
metadata:
  name: rdma-devices
  namespace: kube-system
data:
  config.json: |
    {
      "periodicUpdateInterval": 300,
      "configList": [
        {
          "resourceName": "sounio_gpu_fabric",
          "rdmaHcaMax": 1000,
          "selectors": {
            "vendors": ["15b3"],
            "deviceIDs": ["1017", "1019"],
            "ifNames": ["nic3", "nic4", "ens5f1np1"]
          }
        }
      ]
    }
